config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  
  get "/services", to: "pages#services"
  get "/contact", to: "pages#contact"
  resources :motos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/moto.rb
class Moto < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/motos_controller.rb
class MotosController < ApplicationController

    def index
      @motos = Moto.all
    end
  
    def show
      @moto = Moto.find(params[:id])
    end
  
    def new
      @moto = Moto.new
    end
  
    def create
      @moto = Moto.new(moto_params)
      if @moto.save
        redirect_to moto_path(@moto)
      else
        render :new
      end
    end
  
    def edit
      @moto = Moto.find(params[:id])
    end
  
    def update
      @moto = Moto.find(params[:id])
      @moto.update(moto_params)
      redirect_to moto_path(@moto)
    end
  
    def destroy
      @moto = Moto.find(params[:id])
      @moto.destroy
      redirect_to motos_path
    end
  
    private

    def moto_params
      params.require(:moto).permit(:marque, :modele, :description, :prix, :kilometres, :annee)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home 
    @motos = Moto.all
  end

  def services 
  end

  def contact
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/motos_helper.rb
module MotosHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Temps2chauffe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% unless current_page?(root_path) %> 
    <%= render '/shared/navbar' %>
  <% end %>
      <%= yield %>
  </body>
</html>

app/views/motos/edit.html.erb
<div class="container w-25">
    <%= simple_form_for(@moto) do |f| %>
      <%= f.input :marque %>
      <%= f.input :modele%> 
      <%= f.input :annee%>
      <%= f.input :description%>
      <%= f.submit "EDITER"%>
    <% end %>
</div>

app/views/motos/index.html.erb
<h1 class="title">STOCK MOTOS</h1>
  
    <div class="display-grid w-50 mr-3 ml-5">
      <% @motos.each do |moto| %>
        <%= link_to moto_path(moto) do %>
          <%= render "shared/cards", moto: moto %>
        <% end %>
      <% end %>
    </div>

app/views/motos/new.html.erb
<div class="container w-25">
  
    <%= simple_form_for(@moto) do |f| %>
      <%= f.input :marque %>
      <%= f.input :modele%> 
      <%= f.input :annee%>
      <%= f.input :description%>
      <%= f.submit "CREER"%>
    <% end %>
</div>

app/views/motos/show.html.erb
<div class="container">
 <h2 class="title"> <%= @moto.marque.upcase %> <%= @moto.modele.upcase %>- <%= @moto.annee.upcase %> - <%= @moto.kilometres.upcase %></h2>

<section>
    <div class="container">
        <div class="carousel">
            <input type="radio" name="slides" checked="checked" id="slide-1">
            <input type="radio" name="slides" id="slide-2">
            <input type="radio" name="slides" id="slide-3">
            <input type="radio" name="slides" id="slide-4">
            <input type="radio" name="slides" id="slide-5">
            <input type="radio" name="slides" id="slide-6">
            <ul class="carousel__slides">
                <li class="carousel__slide">
                    <figure>
                        <div>
                            <img src="https://images.unsplash.com/photo-1568708167243-438efa1d7697?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=751&q=80" alt="">
                        </div>
                    </figure>
                </li>
                <li class="carousel__slide">
                    <figure>
                        <div>
                            <img src="https://images.unsplash.com/photo-1516193313597-3ada7b1056a6?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80" alt="">
                        </div>
                    </figure>
                </li>
                <li class="carousel__slide">
                    <figure>
                        <div>
                            <img src="https://images.unsplash.com/photo-1610202926204-c0c9b7d8f112?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=667&q=80" alt="">
                        </div>
                    </figure>
                </li>
                <li class="carousel__slide">
                    <figure>
                        <div>
                            <img src="https://images.unsplash.com/photo-1522850003946-16cb11d41a86?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=750&q=80" alt="">
                        </div>
                    </figure>
                </li>
                <li class="carousel__slide">
                    <figure>
                        <div>
                            <img src="https://images.unsplash.com/photo-1614248888480-7d6ded08ca67?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=625&q=80" alt="">
                        </div>
                    </figure>
                </li>
                <li class="carousel__slide">
                    <figure>
                        <div>
                            <img src="https://images.unsplash.com/photo-1509896209262-537d7f2ef041?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80" alt="">
                        </div>
                    </figure>
                </li>
            </ul>    
            <ul class="carousel__thumbnails">
                <li>
                    <label for="slide-1"><img src="https://images.unsplash.com/photo-1568708167243-438efa1d7697?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=751&q=80" alt=""></label>
                </li>
                <li>
                    <label for="slide-2"><img src="https://images.unsplash.com/photo-1516193313597-3ada7b1056a6?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80" alt=""></label>
                </li>
                <li>
                    <label for="slide-3"><img src="https://images.unsplash.com/photo-1610202926204-c0c9b7d8f112?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=667&q=80" alt=""></label>
                </li>
                <li>
                    <label for="slide-4"><img src="https://images.unsplash.com/photo-1522850003946-16cb11d41a86?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=750&q=80" alt=""></label>
                </li>
                <li>
                    <label for="slide-5"><img src="https://images.unsplash.com/photo-1614248888480-7d6ded08ca67?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=625&q=80" alt=""></label>
                </li>
                <li>
                    <label for="slide-6"><img src="https://images.unsplash.com/photo-1509896209262-537d7f2ef041?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80" alt=""></label>
                </li>
            </ul>
        </div>
    </div>
</section>



    <div class="card-show-infos">
      <p><%= @moto.description %></p>
    </div>
</div>

app/views/pages/contact.html.erb
<h1>contact</h1>

app/views/pages/home.html.erb
<%= render 'shared/banner' %>

<div class="container">
  <div class="card-main">
    <% @motos.last(3).each do |moto| %>
      <div class="card-home">
        <%= link_to moto_path(moto) do %>
          <div class="card-img">
            <img src="https://cdn.pixabay.com/photo/2016/03/27/17/59/motorcycle-1283299_960_720.jpg" alt="photo">
          </div>
              <div class="moto-content">
                <div><%= moto.marque.upcase %></div>
                <div><%= moto.modele.upcase %></div>
                <div><%= moto.annee %></div>
              </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

<%= render 'shared/footer' %>

app/views/pages/services.html.erb
<div class="container">
<h1 class="title">Nos Services</h1>
  <div class="card-product">
      <img src="https://static.wixstatic.com/media/6cbd7f_37adff84790042ea801cce04ab0ab410~mv2_d_3568_2368_s_2.jpg/v1/fill/w_519,h_345,al_c,q_80,usm_0.66_1.00_0.01/6cbd7f_37adff84790042ea801cce04ab0ab410~mv2_d_3568_2368_s_2.webp" />
    <div class="card-product-infos">
      <h2>Rénovation Esthétique</h2>
      <p>
        Nous  réalisons le nettoyage et la rénovation des vos autos et motos de collection. Nous n'utilisons que des produits de qualité comme les  marques Belgom et Meguiar's.</br>
        Nous sommes relativement flexibles et nous adaptons aux souhaits de chaque client, du simple nettoyage au traitement de la carrosserie et des  métaux en </br>
        Nous consulter pour un devis.</br>
      </p>
    </div>
  </div>

  <div class="card-product mt-5">
    <div class="card-product-infos">
      <h2>Transport</h2>
      <p>
        Vous souhaitez acquérir la machine de vos rêves, mais vous n'avez ni le temps ni les moyens matériels pour venir la chercher?</br>
        Aucun problème, nous avons la solution!</br>
        Nous travaillons avec une société uniquement spécialisée dans le transport moto, qui pourra amener votre nouvelle acquisiton où vous le souhaitez en France, et ce en toute sécurité.
        Les motos sont acheminées jusqu'au dépôt de transport où elles sont ensuite placées sur des boxs individuels amovibles. Un état des lieux de la moto est réalisé, puis elle embarque dans un camion jusqu'à chez vous!</br>
      </p>
    </div>
      <img src="https://static.wixstatic.com/media/6cbd7f_d2817fbf5e3444bcb410700f1cfdfbb3~mv2_d_1632_1224_s_2.jpg/v1/fill/w_430,h_305,al_c,q_80,usm_0.66_1.00_0.01/6cbd7f_d2817fbf5e3444bcb410700f1cfdfbb3~mv2_d_1632_1224_s_2.webp" />
  </div>
</div>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://scontent-cdg2-1.xx.fbcdn.net/v/t1.6435-9/201568073_1401720520201237_2032731041336161663_n.jpg?_nc_cat=104&ccb=1-3&_nc_sid=8bfeb9&_nc_ohc=6zDYjLnw174AX8i4nCA&_nc_ht=scontent-cdg2-1.xx&oh=4a2de12df0694f38f0e452912b341079&oe=60F1B251);">
  <div class="bar bg-transparent">
  <div class="logo">
    <a href="/">
      <img src="https://static.wixstatic.com/media/6cbd7f_e3f49a168f664a1cb828257f94deba6b~mv2.png/v1/fill/w_365,h_365,al_c,lg_1,q_85/6cbd7f_e3f49a168f664a1cb828257f94deba6b~mv2.webp" /> 
    </a>
  </div>
  <div class="btn-nav">
    <div>
      <%= link_to "MOTOS", motos_path, class:"motos-home" %>
    </div>
    <div>
      <%= link_to "SERVICES", services_path, class:"services-home" %>
    </div>
    <div>
      <%= link_to "CONTACT", contact_path, class:"contact-home" %>
    </div>
  </div>
</div>
  <div class="container home-content">
    <h1>Spécialisée dans la vente de motos de collection & youngtimers</h1>
    <p>Temps 2 Chauffe propose des machines de qualité, restaurées ou dans un état d'origine exceptionnel.</p>
    <a class="button" href="/motos">Explorer</a>
  </div>
</div>

app/views/shared/_cards.html.erb
<div class="card-trip">
  <img src="https://cdn.pixabay.com/photo/2016/03/27/17/59/motorcycle-1283299_960_720.jpg" />
  <div class="card-trip-infos">
    <div class="infos justify-content-center space-between">
      <p> <%= moto.marque.upcase %> </p>
      <p> <%= moto.modele.upcase %> </p>
      <p> <%= moto.annee %> </p>
    </div>
  </div>
</div>

app/views/shared/_cards_product.erb
<div class="card-product">
  <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
  <div class="card-product-infos">
    <h2>Product name</h2>
    <p>Product description with <strong>relevant info</strong> only.</p>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://www.instagram.com/temps2chauffe/"><i class="fab fa-instagram"></i></a>
    <a href="https://www.facebook.com/temps2chauffe"><i class="fab fa-facebook"></i></a>
  </div>
  <div class="footer-copyright">
    Temps 2 Chauffe/Tous droits réservés.
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="bar bg-transparent">
  <div class="logo">
    <a href="/">
      <img src="https://static.wixstatic.com/media/6cbd7f_e3f49a168f664a1cb828257f94deba6b~mv2.png/v1/fill/w_365,h_365,al_c,lg_1,q_85/6cbd7f_e3f49a168f664a1cb828257f94deba6b~mv2.webp" /> 
    </a>
  </div>
  <div class="btn-nav">
    <div>
      <%= link_to "MOTOS", motos_path, class:"motos" %>
    </div>
    <div>
      <%= link_to "SERVICES", services_path, class:"services" %>
    </div>
    <div>
      <%= link_to "CONTACT", contact_path, class:"contact" %>
    </div>
  </div>
</div>